export const OBTER_PROJETOS = 'OBTER_PROJETOS'
export const CADASTRAR_PROJETO = 'CADASTRAR_PROJETO'
export const ALTERA_PROJETO = 'ALTERA_PROJETO'
export const REMOVER_PROJETO = 'REMOVER_PROJETO'

export const OBTER_TAREFAS = 'OBTER_TAREFAS'
export const CADASTRAR_TAREFA = 'CADASTRAR_TAREFA'